# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [6]:
print(np.__version__, np.show_config())



{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [21]:
a = np.random.randint(10, size=(2, 3, 5))
print(a)

# b = np.random.randint(0, 100, size=(5, 2, 3))
# print(b)




[[[7 0 0 6 0]
  [1 6 8 7 4]
  [6 5 6 3 4]]

 [[9 8 7 9 1]
  [2 6 1 1 6]
  [1 6 9 6 7]]]



### 4. Print a.


In [22]:
### [your code here]
print(a)

[[[7 0 0 6 0]
  [1 6 8 7 4]
  [6 5 6 3 4]]

 [[9 8 7 9 1]
  [2 6 1 1 6]
  [1 6 9 6 7]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [23]:
### [your code here]
b = np.ones((5, 2, 3))



### 6. Print b.


In [24]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [27]:
### [your code here

compare = np.array_equal(a, b)
print(compare)



False



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
#No you cannot add a + b, because the shapes of the arrays are different even though the values are similar. You would need to reshape the arrays to make them suitable for addition. 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
### [your code here]
c = np.transpose(b, (1, 2, 0))
print(c)



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d = a + c
print(d)
#it works now because the 3d arrays are the same shape

[[[ 8.  1.  1.  7.  1.]
  [ 2.  7.  9.  8.  5.]
  [ 7.  6.  7.  4.  5.]]

 [[10.  9.  8. 10.  2.]
  [ 3.  7.  2.  2.  7.]
  [ 2.  7. 10.  7.  8.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print(a)
print(d)

#all the valies have been added together in their same index and turned into explicit integers with a decimal


[[[7 0 0 6 0]
  [1 6 8 7 4]
  [6 5 6 3 4]]

 [[9 8 7 9 1]
  [2 6 1 1 6]
  [1 6 9 6 7]]]
[[[ 8.  1.  1.  7.  1.]
  [ 2.  7.  9.  8.  5.]
  [ 7.  6.  7.  4.  5.]]

 [[10.  9.  8. 10.  2.]
  [ 3.  7.  2.  2.  7.]
  [ 2.  7. 10.  7.  8.]]]



### 12. Multiply a and c. Assign the result to e.


In [36]:
### [your code here]
e = a * c
print(e)


[[[7. 0. 0. 6. 0.]
  [1. 6. 8. 7. 4.]
  [6. 5. 6. 3. 4.]]

 [[9. 8. 7. 9. 1.]
  [2. 6. 1. 1. 6.]
  [1. 6. 9. 6. 7.]]]




### 13. Does e equal to a? Why or why not?


In [41]:
### [your code here]

#the values are similar but not the same. e array is populated with floating-point numbers and a is populated by ints. so while the return the same value for comparisons,they are not the same types which can mess with operations. 




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [43]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)


10.0 1.0 5.733333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [50]:
### [your code here]
f = np.empty([2, 3, 5])
print(f)


[[[ 8.  1.  1.  7.  1.]
  [ 2.  7.  9.  8.  5.]
  [ 7.  6.  7.  4.  5.]]

 [[10.  9.  8. 10.  2.]
  [ 3.  7.  2.  2.  7.]
  [ 2.  7. 10.  7.  8.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
f[(f > d_min) & (f < d_mean)] = 25
f[(f > d_mean) & (f < d_max)] = 75
f[f == d_mean] = 50
f[f == d_min] = 0
f[f == d_max] = 100

print(f)




[[[ 75.   0.   0.  75.   0.]
  [ 25.  75.  75.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[100.  75.  75. 100.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75. 100.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [55]:
### [your code here]
print(d)
print(f)

[[[ 8.  1.  1.  7.  1.]
  [ 2.  7.  9.  8.  5.]
  [ 7.  6.  7.  4.  5.]]

 [[10.  9.  8. 10.  2.]
  [ 3.  7.  2.  2.  7.]
  [ 2.  7. 10.  7.  8.]]]
[[[ 75.   0.   0.  75.   0.]
  [ 25.  75.  75.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[100.  75.  75. 100.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75. 100.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]